### ISSUE TITLE
Error: Cannot read property '0' of null

### ISSUE THREAD

**Issue by eric12s** [vercel/next-server-components#5]
Hey,
I'm trying to run the demo but unfortunately, I'm getting the error "Error: Cannot read property '0' of null".
`Call Stack
Object.get
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (133:361419)
<unknown>
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:1613)
Array.toJSON
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:2690)
stringify
<anonymous>
<unknown>
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:4571)
x
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:4640)
k
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:4910)
Immediate._onImmediate
file:///C:/Users/erics/Desktop/Web/server-component-next/next-server-components/.next/server/pages/api.js (140:6342)
processImmediate
internal/timers.js (456:21)`

Is the demo still supported?

**Comment by huozhi** [comment]
It's rewritten with nextjs 12 now, please try again 🙏
